language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --all
  - cargo test --all